apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo1m.fullname" . }}-app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo1m.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo1m.fullname" . }}-db-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo1m.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: {{ printf "postgres://%s:%s@%s-postgres:5432/%s?sslmode=disable" .Values.postgres.auth.username .Values.postgres.auth.password (include "todo1m.fullname" .) .Values.postgres.auth.database | quote }}
