global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: command-api
    static_configs:
      - targets: ["command-api:8080"]

  - job_name: sse-streamer
    static_configs:
      - targets: ["sse-streamer:8081"]

  - job_name: domain-engine
    static_configs:
      - targets: ["domain-engine:8082"]

  - job_name: data-sink
    static_configs:
      - targets: ["data-sink:8083"]

  - job_name: load-generator
    static_configs:
      - targets: ["load-generator:9099"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: nats-exporter
    static_configs:
      - targets: ["nats-exporter:7777"]
