apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ../05-app-workloads.yaml

images:
  - name: ghcr.io/lieranderl/todo-1m-command-api
    newName: todo-1m/command-api
    newTag: latest
  - name: ghcr.io/lieranderl/todo-1m-sse-streamer
    newName: todo-1m/sse-streamer
    newTag: latest
  - name: ghcr.io/lieranderl/todo-1m-domain-engine
    newName: todo-1m/domain-engine
    newTag: latest
  - name: ghcr.io/lieranderl/todo-1m-data-sink
    newName: todo-1m/data-sink
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: command-api
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets
  - target:
      kind: Deployment
      name: sse-streamer
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets
  - target:
      kind: Deployment
      name: domain-engine
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets
  - target:
      kind: Deployment
      name: data-sink
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets
